name: Tests unitaire Javascript
on:
  push:
    branches:
      - dev1.0
  pull_request:
    branches:
      - dev1.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Give Jest permission
      run: chmod +x node_modules/.bin/jest

    - name: Run tests
      run: npm run test
